I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/game_content/start.rpy", line 7, in script
    $ renpy.start.play("ES_A Hard Truth - Wanderer's Trove.mp3")
  File "game/scripts/game_content/start.rpy", line 7, in <module>
    $ renpy.start.play("ES_A Hard Truth - Wanderer's Trove.mp3")
AttributeError: module 'renpy.exports' has no attribute 'start'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/game_content/start.rpy", line 7, in script
    $ renpy.start.play("ES_A Hard Truth - Wanderer's Trove.mp3")
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\ast.py", line 827, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/scripts/game_content/start.rpy", line 7, in <module>
    $ renpy.start.play("ES_A Hard Truth - Wanderer's Trove.mp3")
AttributeError: module 'renpy.exports' has no attribute 'start'

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.4.24120703
 1.0
Tue Mar  4 17:56:50 2025
