I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/game_content/herb_gathering.rpy", line 104, in script
    call screen herb_gathering_screen
ScriptError: could not find label 'herb3_collected'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\main.py", line 652, in main
    run(restart)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\main.py", line 148, in run
    renpy.execution.run_context(True)
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\execution.py", line 958, in run_context
    context.run()
  File "game/scripts/game_content/herb_gathering.rpy", line 104, in script
    call screen herb_gathering_screen
  File "C:\Users\annie\Downloads\renpy-8.3.4-sdk\renpy\script.py", line 1103, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'herb3_collected'.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.4.24120703
 1.0
Tue Apr  1 19:10:59 2025
